version: '3'


networks:
  my-registry-net:
    driver: bridge

volumes:
  my-registry-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

  my-portainer-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./portainer


services:

  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000

    environment:
      # for https
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_HTTP_SECRET: supersecuresecret
      # for authentication
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      # for image saving
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      # for ui
      #REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[https://registry:5000]'
      #REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      #REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      #REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      #REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

    volumes:
      - my-registry-data:/data
      - ./certs:/certs
      - ./auth:/auth

    networks:
      - my-registry-net


  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always

    environment:
      REGISTRY_TITLE: FlagFrenzy | Registry
      #REGISTRY_HOST: registry:5000
      #NGINX_PROXY_PASS_URL: https://nginx:8443/v2/
      REGISTRY_SECURED: true
      SINGLE_REGISTRY: true
      DELETE_IMAGES: true
      SHOW_CONTENT_DIGEST: true
      SHOW_CATALOG_NB_TAGS: true
      TAGLIST_PAGE_SIZE: 100
      CATALOG_ELEMENTS_LIMIT: 10
      THEME: dark

      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password

    depends_on:
      - registry

    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./auth:/auth

    networks:
      - my-registry-net


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8443:443

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

    depends_on:
      - registry
      - registry-ui

    networks:
      - my-registry-net


  portainer:
    image: portainer/portainer-ce
    ports:
      - 9443:9443

    restart: on-failure

    volumes:
      - my-portainer-data:/data
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock #Portainer - rootless mount

    networks:
      - my-registry-net
